crm_name: Nylas' CRM
calendar_name: Nylas CRM Calendar
calendar_description: Calendar for the Nylas CRM
background_image: NylasDesktop.png 
background_color: 4169E0
panel_color: bg-blue-300
panel_border: border-blue-300
limit: 4
email_limit: 10
fetch_emails: 30
